#!/usr/bin/env bash
#
# audit-checklist.sh — read-only infrastructure audit
#
# Runs six probe areas (SSH, TLS/headers, exposed paths, CMS-specific, DB exposure,
# secrets & DNS) and emits a markdown report on stdout.
#
# Safe to run on production — no writes, no service restarts. Probes are simple
# `curl`, `dig`, `ss`, and file-read calls.
#
# Usage:
#   ./audit-checklist.sh > audit-report-$(date -u +%Y%m%dT%H%M%SZ).md
#
# Configure the four lists below for your estate.

set -euo pipefail

# ---- CONFIG (edit per estate) ------------------------------------------------

# Domains to probe for TLS, headers, and exposed paths.
DOMAINS=(
  "<DOMAIN_1>"
  "<DOMAIN_2>"
)

# WordPress sites to probe for REST API user enumeration.
WP_SITES=(
  "<WP_DOMAIN_1>"
)

# Authoritative nameservers to probe for AXFR.
AUTH_NS=(
  "<NS_1>"
  "<NS_2>"
)

# Hosts running PostgreSQL/MariaDB whose listeners we check via local ss.
DB_HOSTS=(
  "<DB_HOST_1>"
)

# Paths considered sensitive if they 200 over HTTPS.
EXPOSED_PATHS=(
  "/.git/HEAD"
  "/.env"
  "/composer.json"
  "/wp-config.bak"
  "/wp-config.php.bak"
  "/phpinfo.php"
  "/server-status"
  "/server-info"
  "/adminer.php"
  "/pma/"
)

# ---- HELPERS -----------------------------------------------------------------

red()   { printf "\033[31m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
amber() { printf "\033[33m%s\033[0m\n" "$*"; }

probe_path() {
  local domain="$1"; local path="$2"
  local code
  code=$(curl -sk -o /dev/null -w '%{http_code}' --max-time 8 "https://${domain}${path}" || echo "000")
  echo "$code"
}

probe_header() {
  local domain="$1"; local header="$2"
  curl -skI --max-time 8 "https://${domain}/" 2>/dev/null | grep -iE "^${header}:" | head -1 || echo ""
}

# ---- HEADER ------------------------------------------------------------------

cat <<EOF
# Audit report — $(date -u +%Y-%m-%dT%H:%M:%SZ)

Generated by \`audit-checklist.sh\`. Read-only probes only.

EOF

# ---- 1. SSH ------------------------------------------------------------------

cat <<EOF
## 1. SSH

Reading \`/etc/ssh/sshd_config\` for risky defaults.

EOF

if [[ -r /etc/ssh/sshd_config ]]; then
  for key in PermitRootLogin PasswordAuthentication MaxAuthTries LoginGraceTime AllowGroups AllowUsers; do
    line=$(grep -E "^\s*${key}\b" /etc/ssh/sshd_config | head -1 || echo "(unset — default)")
    echo "- \`${key}\`: ${line}"
  done

  echo
  echo "Dormant accounts (no login in 60 days):"
  if command -v lastlog >/dev/null 2>&1; then
    lastlog -b 60 2>/dev/null | awk 'NR>1 && $0 !~ /Never logged in/ {print "- " $1}' | head -20 || echo "- (none)"
  else
    echo "- (lastlog not available)"
  fi
else
  echo "- /etc/ssh/sshd_config not readable. Skipping SSH probe."
fi

# ---- 2. TLS + HTTP headers ---------------------------------------------------

cat <<EOF

## 2. TLS / HTTP headers

For each domain, check presence of HSTS, CSP, X-Frame-Options, Referrer-Policy.

EOF

for d in "${DOMAINS[@]}"; do
  echo "### ${d}"
  for h in Strict-Transport-Security Content-Security-Policy X-Frame-Options Referrer-Policy Permissions-Policy Server X-Powered-By; do
    val=$(probe_header "$d" "$h")
    if [[ -z "$val" ]]; then
      echo "- ${h}: **(missing)**"
    else
      echo "- ${h}: \`$(echo "$val" | tr -d '\r')\`"
    fi
  done
  echo
done

# ---- 3. Exposed paths --------------------------------------------------------

cat <<EOF
## 3. Exposed paths

A 200/301/302 on any of these paths is suspicious. 401/403/404 are good.

| Domain | Path | HTTP |
|---|---|---|
EOF

for d in "${DOMAINS[@]}"; do
  for p in "${EXPOSED_PATHS[@]}"; do
    code=$(probe_path "$d" "$p")
    if [[ "$code" == "200" || "$code" == "301" || "$code" == "302" ]]; then
      echo "| ${d} | \`${p}\` | **${code}** |"
    fi
  done
done

# ---- 4. CMS-specific ---------------------------------------------------------

cat <<EOF

## 4. CMS-specific (WordPress REST user enum)

EOF

for d in "${WP_SITES[@]}"; do
  body=$(curl -sk --max-time 8 "https://${d}/wp-json/wp/v2/users" || echo "")
  if echo "$body" | grep -qE '"slug"|"name"'; then
    echo "- **${d}**: REST users endpoint LEAKS data."
  else
    echo "- ${d}: REST users endpoint locked or returns no user list."
  fi
done

# ---- 5. DB exposure ----------------------------------------------------------

cat <<EOF

## 5. DB exposure (local ss probe)

Run on each DB host. Lines matching 0.0.0.0 are public listeners — investigate.

EOF

if command -v ss >/dev/null 2>&1; then
  ss -tlnp 2>/dev/null | grep -E ':(5432|3306|5433|3307)\b' | sed 's/^/    /' || echo "- (no DB listeners visible)"
else
  echo "- ss not available."
fi

# ---- 6. Secrets & DNS --------------------------------------------------------

cat <<EOF

## 6. Secrets & DNS

### World-readable .env / credentials in webroots

EOF

find /var/www /srv/www /home/*/web -maxdepth 5 -name ".env" -type f -perm /004 2>/dev/null | sed 's/^/- /' || true
find /var/www /srv/www /home/*/web -maxdepth 5 -name "*.env" -type f -perm /004 2>/dev/null | sed 's/^/- /' || true

echo
echo "### DNS AXFR open?"
for ns in "${AUTH_NS[@]}"; do
  for d in "${DOMAINS[@]}"; do
    out=$(dig +short +time=4 +tries=1 axfr @"$ns" "$d" 2>/dev/null | head -1)
    if [[ -n "$out" && ! "$out" =~ "transfer failed" ]]; then
      echo "- **${d} @ ${ns}**: AXFR returns data — restrict with \`allow-transfer\`."
    else
      echo "- ${d} @ ${ns}: AXFR closed (good)."
    fi
  done
done

cat <<EOF

---

End of report. Triage findings into CRITICAL / HIGH / MEDIUM / LOW and proceed with
the [8-phase remediation pattern](./8-phase-remediation-pattern.md).
EOF
